version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: taller_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taller_mecanico
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Mapeamos tus scripts de inicialización sql desde la nueva ruta del backend
      - ./taller-backend/database/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: taller_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@taller.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy

  # Agregamos servicio Backend
  backend:
    build:
      context: ./taller-backend
      dockerfile: Dockerfile
    container_name: taller_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_HOST=postgres  # Apunta al servicio 'postgres' de arriba
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=taller_db_f0r4
    depends_on:
      postgres:
        condition: service_healthy # Espera a que la BD esté realmente lista

  # Agregamos servicio Frontend
  frontend:
    build:
      context: ./taller-frontend
      dockerfile: Dockerfile
    container_name: taller_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data: